language: cpp
sudo: false

env:
  global:
    - OMP_NUM_THREADS=4

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libboost-dev']
      env: COMPILER=g++-5

  # - os: linux
  #   compiler: clang++
  #   addons:
  #     apt:
  #       sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
  #       packages: ['g++-5', 'clang-3.8', 'libboost-dev']
  #   env: COMPILER=clang++-3.8

script:
  - make clean
  - make all -j4 CXX=$COMPILER

