language: cpp
sudo: false

cache:
  - apt

env:
  global:
    - OMP_NUM_THREADS=4

matrix:
  include:
    - os: linux
      compiler: g++-5

    #- os: linux
    #  compiler: clang++-3.8

addons:
  apt:
    sources:
      #- llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      #- clang-3.8
      #- libomp-dev
      - libboost-dev

script:
  - if [ "$CXX" == "g++"     ] ; then export CXX="g++-5"       ; fi
  - if [ "$CXX" == "clang++" ] ; then export CXX="clang++-3.8" ; fi
  - make clean
  - make all -j4

